
import { LyricLine } from '../types';

export const LYRICS: LyricLine[] = [
  { time: 0, text: "De Volta no Twist - ConeCrewDiretoria", isStrong: true },
  { time: 3, text: "Qual é o nome do bonde?" },
  { time: 4.5, text: "O nome do bonde é Família Corleone", isStrong: true },
  { time: 7.5, text: "Eu sigo com a Cone no fone apertando uns cone" },
  { time: 10, text: "Foda-se os \"homi\", se eles aparece, sem stress" },
  { time: 13, text: "Rapidinho a gente some" },
  { time: 15, text: "Eu taco a bomba de fumaça" },
  { time: 17.5, text: "Quando eu tô com os meus parceiros lá na praça" },
  { time: 20, text: "\"Tá ele e dois comparsa\"", isStrong: true },
  { time: 22, text: "Um de camisa do flamengo e outro do Barça" },
  { time: 25, text: "bonezinho de aba reta" },
  { time: 27, text: "Tranquilo, meu parceiro, a minha ideia é sempre reta" },
  { time: 31, text: "Não faz curva, mesmo que a minha visão esteja turva" },
  { time: 34, text: "Pode bater o tambor e botar meu nome na macumba" },
  { time: 37, text: "Volta em outra segunda, nós tá trabalhando" },
  { time: 40, text: "Enquanto tu ta falando merda e dando a bunda" },
  { time: 43, text: "Comédia pela saco" },
  { time: 45, text: "Se tu insistir nesse papo eu vou ter que te dar um papo assim" },
  { time: 48, text: "Vê se acorda, porque quem é pela saco a gente só da corda" },
  { time: 52, text: "que ele se enforca" },
  { time: 54, text: "Depois a gente aplaude igual uma foca" },
  { time: 56, text: "Foda-se esses \"mothafucka\" que fazem fofoca" },
  { time: 59, text: "\"Pra mim é desculpa esses troços de rap\"", isStrong: true },
  { time: 62, text: "Foda-se, faço essa merda desde muleke" },
  { time: 65, text: "Meu nome é Rany money e o apelido é Jack" },
  { time: 68, text: "Joga no Google se tu não conhece" },
  { time: 71, text: "Eu não sou Paulinho Gogó, mas tô de volta no twist", isStrong: true },
  { time: 74, text: "Vou ligar pro papatinho e mandar eles fazer uns beats" },
  { time: 77, text: "Não sou Bob Burnquist, mas volto uns mctwist" },
  { time: 81, text: "Vou ficar tranquilo com as mina de sanduíche" },
  { time: 84, text: "Eu não sou Paulinho Gogó, mas tô de volta no twist", isStrong: true },
  { time: 87, text: "Vai tabaco, vai haxixe, só pra começar o meu mix" },
  { time: 90, text: "Eu sou vagabundo mermo, 10 horas de Netflix" },
  { time: 93, text: "Mas vou ficar tranquilo com as minas de sanduíche" },
  { time: 96, text: "Ow shit, I love you bitch" },
  { time: 98, text: "Vou ficar tranquilo com as minas de celulite (ahhh)" },
  { time: 101, text: "Meu bonde tá aqui comigo, ninguém vai ficar de pista" },
  { time: 104, text: "132 Amigos já tão com o nome na lista" },
  { time: 107, text: "Em roda de cachaça meus amigos mandam free" },
  { time: 110, text: "Meu camarim fede a xixi, mas pelo menos tem sushi (yess!)" },
  { time: 113, text: "Tem uns cara que tem jet e até iate pra passeio (haha)" },
  { time: 116, text: "Tô de bike com os \"mulekes\" na orla aqui do recreio" },
  { time: 119, text: "Eu não sou Paulinho Gogó, mas tô de volta no twist", isStrong: true },
  { time: 122, text: "Vou ligar pro papatinho e mandar eles fazer uns beats" },
  { time: 125, text: "Não sou Bob Burnquist, mas volto uns mctwist" },
  { time: 128, text: "Vou ficar tranquilo com as mina de sanduíche" },
  { time: 132, text: "Não gosto muito de nada, prazer cert da cone" },
  { time: 135, text: "Ou Tony Montana, Escobar, Corleone (ahhh)" },
  { time: 138, text: "Aí tu para de caô, sem essa" },
  { time: 141, text: "É porque esse bandidão do rap correm quando o tempo fecha" },
  { time: 144, text: "Quero minha parte, tô bem" },
  { time: 146, text: "Que nunca falte as de 100" },
  { time: 148, text: "E as piriguete quando bate querem meu ret do glen" },
  { time: 151, text: "Eu sou tcer, aquele que as mulé quer" },
  { time: 154, text: "E a pistoleira \"qué\" carteira amarrada no pau em pé (coé)" },
  { time: 157, text: "Eu to de volta no twist" },
  { time: 160, text: "Esquisito eu fico depois de quinze doses de whisky (ahhh)" },
  { time: 163, text: "Meu cachorro quer passear" },
  { time: 165, text: "Sem coleira, eu cheio de olheira, em plena sexta-feira" },
  { time: 168, text: "Com a rua inteira cheia, eu passo com pé sem meia" },
  { time: 171, text: "Descalço com a cara feia, moicano e barba mal feita" },
  { time: 174, text: "Um foda-se na minha cabeça somente pra explicar" },
  { time: 177, text: "Vai tomar no cu pra lá quem vem pra atrapalhar" },
  { time: 180, text: "A maioria só quer criticar" },
  { time: 182, text: "Assim só vai conseguir me inspirar" },
  { time: 185, text: "E agora eu vou me preocupar pra que?" },
  { time: 188, text: "Só vou ficar tranquilo com as mina de sanduíche" },
  { time: 191, text: "Eu não sou Paulinho Gogó, mas tô de volta no twist", isStrong: true },
  { time: 194, text: "Vou ligar pro papatinho e mandar eles fazer uns beats" },
  { time: 197, text: "Não sou Bob Burnquist, mas volto uns mctwist" },
  { time: 200, text: "Vou ficar tranquilo com as mina de sanduíche" }
];
